frameworkVersion: "=1.26.0"
service: myMultiStackApi

provider:
  name: aws
  runtime: nodejs6.10
  region: ${opt:region, 'us-east-1'}
  stage: ${opt:stage, 'development'}
  package:
    individually: true
  environment:
    pingsTableName: ${cf:myMultiStackResources-${self:provider.stage}.pingsTableName}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:PutItem
      Resource:
        - 'Fn::Join':
          - ':'
          -
            - 'arn:aws:dynamodb'
            - Ref: 'AWS::Region'
            - Ref: 'AWS::AccountId'
            - 'table/${cf:myMultiStackResources-${self:provider.stage}.pingsTableName}'

plugins:
  - serverless-webpack

custom:
  webpackIncludeModules: true

functions:
  pingPost:
    handler: src/handlers/ping.postHandler
    events:
      - http:
          path: ping
          method: post
          cors: true
  pingGet:
    handler: src/handlers/ping.getHandler
    events:
      - http:
          path: ping
          method: get
          cors: true
